import { Injectable, Logger } from '@nestjs/common';
import { JwtService, JwtSignOptions } from '@nestjs/jwt';
import { ConfigService } from '@nestjs/config';

export interface TokenPayload {
  sub: string;
  type: string;
  [key: string]: unknown;
}

@Injectable()
export class TokenService {
  private readonly logger = new Logger(TokenService.name);

  constructor(
    private jwtService: JwtService,
    private configService: ConfigService,
  ) {}

  /**
   * Generates a signed JWT token for non-auth purposes
   * (invitations, public quote links, client invite tokens, etc.)
   */
  generate(payload: TokenPayload, expiresIn = '7d'): string {
    const options: JwtSignOptions = {
      secret: this.configService.getOrThrow<string>('JWT_SECRET'),
      expiresIn: expiresIn as JwtSignOptions['expiresIn'],
    };
    return this.jwtService.sign(payload, options);
  }

  /**
   * Verifies a token generated by this service.
   * Returns the payload or null if invalid/expired.
   */
  verify(token: string): TokenPayload | null {
    try {
      return this.jwtService.verify<TokenPayload>(token, {
        secret: this.configService.getOrThrow<string>('JWT_SECRET'),
      });
    } catch (error) {
      this.logger.debug(
        `Token verification failed: ${error instanceof Error ? error.message : 'unknown'}`,
      );
      return null;
    }
  }

  /**
   * Verifies and checks the token type.
   * Returns null if invalid or wrong type.
   */
  verifyWithType(token: string, expectedType: string): TokenPayload | null {
    const payload = this.verify(token);
    if (!payload || payload.type !== expectedType) {
      return null;
    }
    return payload;
  }
}
